version: '3'
name: garoo
services:
  garoo:
    # image: rot1024/garoo
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./garoo.db:/app/garoo.db
    env_file:
      - ./.env
    restart: unless-stopped
